version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: progzone2-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: progzone2-web
    restart: unless-stopped
    ports:
      - "8020:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: progzone2-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: progzone2
      MYSQL_ROOT_PASSWORD: progzone2
      MYSQL_USER: progzone2
      MYSQL_PASSWORD: progzone2
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/arm64/v8
    container_name: progzone2-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: progzone2
    ports:
      - "8082:80"

volumes:
  dbdata: